web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'ec2-18-218-145-138.us-east-2.compute.amazonaws.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://ec2-18-218-145-138.us-east-2.compute.amazonaws.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '443:443'
    - '2222:22'
  volumes:
    - '/home/ubuntu/gitlab/config:/etc/gitlab'
    - '/home/ubuntu/gitlab/logs:/var/log/gitlab'
    - '/home/ubuntu/gitlab/data:/var/opt/gitlab'
